[project]
name = "diff-delay-net"
version = "0.1.0"
description = "A project for diff-delay-net"
authors = [
    { name="Gloria Dal Santo", email="gloria.dalsanto@aalto.di" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "torchaudio",
    "numpy",
    "soundfile",
    "tqdm",
    "scipy",
    "pandas",
    "webdataset",
    "nnAudio",
    "tqdm",
    "einops"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"